[package]
name = "neuron-orch-local"
version = "0.1.0"
edition = "2021"
description = "In-process Orchestrator implementation for neuron"
license = "MIT OR Apache-2.0"
repository = "https://github.com/secbear/neuron"

[dependencies]
layer0 = { path = "../layer0" }
async-trait = "0.1"
tokio = { version = "1", features = ["rt", "sync"] }
serde_json = "1"

[dev-dependencies]
layer0 = { path = "../layer0", features = ["test-utils"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1"
