[package]
name = "neuron-turn"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "ReAct loop implementing layer0::Turn"

[dependencies]
layer0 = { path = "../layer0" }
neuron-tool = { path = "../neuron-tool" }
neuron-hooks = { path = "../neuron-hooks" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1"
thiserror = "2"
rust_decimal = { version = "1", features = ["serde-str"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
